services:
  dummy-university-service:
    container_name: dummy-university-service
    image: dummy-university-service
    build: .
    ports:
      - "9001:9001"
    networks:
      - thesis_fdsl_net

networks:
  thesis_fdsl_net:
    external: true
