version: '3.8'

services:
  dummy-profile:
    build:
      context: .
      dockerfile: Dockerfile.dummy
    container_name: profile-dummy
    ports:
      - "9001:9001"
    networks:
      - thesis_fdsl_net

networks:
  thesis_fdsl_net:
    external: true
