version: '3.8'

services:
  dummy-user-service:
    build: ./user-service
    container_name: dummy-user-service
    ports:
      - "8001:8001"
    networks:
      - thesis_fdsl_net
    restart: unless-stopped

  dummy-order-service:
    build: ./order-service
    container_name: dummy-order-service
    ports:
      - "8002:8002"
    networks:
      - thesis_fdsl_net
    restart: unless-stopped

networks:
  thesis_fdsl_net:
    external: true
