services:
  dummy-text-service:
    container_name: dummy-text-service
    image: dummy-text-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9800:9800"
    networks:
      - thesis_fdsl_net

networks:
  thesis_fdsl_net:
    external: true
