version: '3.8'

services:
  dummy-rest-patterns:
    build: .
    container_name: dummy-rest-patterns
    ports:
      - "9001:9001"
    networks:
      - thesis_fdsl_net

networks:
  thesis_fdsl_net:
    external: true
