version: '3.8'

services:
  dummy-echo-service:
    container_name: dummy-echo-service
    image: dummy-echo-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8765:8765"
    networks:
      - thesis_fdsl_net

networks:
  thesis_fdsl_net:
    external: true
