version: '3.8'

services:
  dummy-restaurant:
    build:
      context: .
      dockerfile: Dockerfile.dummy
    container_name: dummy-restaurant
    ports:
      - "9001:9001"
    networks:
      - thesis_fdsl_net
    environment:
      - FLASK_ENV=development
    restart: unless-stopped

networks:
  thesis_fdsl_net:
    external: true
