version: '3.8'

services:
  dummy-user-orders-service:
    build: . 
    container_name: dummy-user-orders-service
    ports:
      - "9001:9001"
    networks:
      - thesis_fdsl_net

networks:
  thesis_fdsl_net:
    external: true
