version: '3.8'

services:
  dummy-library:
    container_name: dummy-library
    build: .
    ports:
      - "9200:9200"
    networks:
      - thesis_fdsl_net

networks:
  thesis_fdsl_net:
    external: true
