version: "3.9"

networks:
  thesis_fdsl_net:
    external: true

services:
  dummy-product-service:
    build: ./product-service
    container_name: dummy-product-service
    image: dummy-product-service
    ports:
      - "9001:9001"
    restart: unless-stopped
    networks:
      - thesis_fdsl_net

  dummy-cart-service:
    build: ./cart-service
    container_name: dummy-cart-service
    image: dummy-cart-service
    ports:
      - "9002:9002"
      - "9003:9003"  # WebSocket port
    restart: unless-stopped
    networks:
      - thesis_fdsl_net
