version: "3.8"

networks:
  thesis_fdsl_net:
    external: true

services:
  # Combined dummy service (all endpoints on one service for simplicity)
  dummy-ecomm-service:
    build: .
    container_name: dummy-ecomm-service
    ports:
      - "9001:9001"
    networks:
      - "thesis_fdsl_net"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9001/"]
      interval: 10s
      timeout: 5s
      retries: 3
