version: '3.8'

services:
  dummy-social-analytics:
    build:
      context: .
      dockerfile: Dockerfile.dummy
    container_name: dummy-social-analytics
    ports:
      - "9001:9001"
    networks:
      - thesis_fdsl_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9001/health"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  thesis_fdsl_net:
    external: true
