services:
  dummy-large-data:
    container_name: dummy-large-data
    image: dummy-large-data
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    networks:
      - thesis_fdsl_net

networks:
  thesis_fdsl_net:
    external: true
