services:
  dummy-user-service:
    container_name: dummy-user-service
    image: dummy-user-service
    build:
      context: .
      dockerfile: Dockerfile.user
    ports:
      - "9001:9001"
    networks:
      - thesis_fdsl_net

  dummy-product-service:
    container_name: dummy-product-service
    image: dummy-product-service
    build:
      context: .
      dockerfile: Dockerfile.product
    ports:
      - "9002:9002"
    networks:
      - thesis_fdsl_net

  dummy-inventory-service:
    container_name: dummy-inventory-service
    image: dummy-inventory-service
    build:
      context: .
      dockerfile: Dockerfile.inventory
    ports:
      - "9003:9003"
    networks:
      - thesis_fdsl_net

  dummy-order-service:
    container_name: dummy-order-service
    image: dummy-order-service
    build:
      context: .
      dockerfile: Dockerfile.order
    ports:
      - "9004:9004"
    networks:
      - thesis_fdsl_net

networks:
  thesis_fdsl_net:
    external: true
