services:
  dummy-order-service:
    container_name: dummy-order-service
    image: dummy-order-service
    build: .
    ports:
      - "9001:9001"
    networks:
      - thesis_fdsl_net

networks:
  thesis_fdsl_net:
    external: true
