version: "3.9"

networks:
  thesis_fdsl_net:
    external: true

services:
  dummycamera:
    image: node:20-alpine
    container_name: dummycamera
    working_dir: /app
    command: sh -c "npm install && node server.js"
    volumes:
      - .:/app
      - ../vidf1_33_000.y:/app/vidf1_33_000.y:ro
    ports:
      - "9700:9700"
    restart: unless-stopped
    networks:
      - thesis_fdsl_net
