services:
  dummy-storage:
    container_name: dummy-storage
    image: dummy-storage-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9900:9900"
    networks:
      - thesis_fdsl_net

networks:
  thesis_fdsl_net:
    external: true
